- name: configure nodejs nodejs
  hosts: _ansible_nodejs
  become: true
  tasks:
    - name: upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Uninstall old versions
      ansible.builtin.yum:
        name: 
         - docker
         - docker-client
         - docker-client-latest
         - docker-common
         - docker-latest
         - docker-latest-logrotate
         - docker-logrotate
         - docker-engine
         - podman
         - runc
        state: removed

    - name: install dnf-plugin
      ansible.builtin.yum:
        name: dnf-plugins-core
        state: latest

    - name: add docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo 

    - name: install docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
  # sudo usermod -a -G docker ec2-user

    - name: start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      
    - name: copy files to the nodejs node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/nodejs/
        dest: /home/ec2-user/nodejs

  # Remove the container if it exists
    - name: remove td_nodejs container
      community.docker.docker_container:
        name: td_nodejs
        state: absent
        force_kill: true

  # Remove the image if it exists
    - name: remove todo/nodejs image
      community.docker.docker_image:
        name: todo/nodejs
        state: absent

    - name: build container image
      community.docker.docker_image:
        name: todo/nodejs
        build:
          path: /home/ec2-user/nodejs
        source: build
        state: present
      register: image_info

    - name: print the image info
      ansible.builtin.debug:
        var: image_info

    - name: Launch nodejs docker container
      community.docker.docker_container:
        name: td_nodejs
        image: todo/nodejs
        state: started
        ports: 
        - "5000:5000"
      register: container_info
    
    - name: print the container info
      ansible.builtin.debug:
        var: container_info